# Generated by Django 4.2.10 on 2024-03-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Done', 'Done'), ('InPr', 'InProgress')], default='Todo', max_length=4),
        ),
    ]
