# Generated by Django 4.2.10 on 2024-03-05 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
